site_name: ReSim Core Documentation

site_url: http://resim-docs-prod.s3-website-us-west-1.amazonaws.com

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

dev_addr: 0.0.0.0:8080

theme:
    name: readthedocs
    highlightjs: true
