name: Lint & Generate CodeCov Report
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Lint & Generate Coverage Report
    runs-on: ubuntu-20.04
    container:
      image: public.ecr.aws/m1r4u2a2/core:latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Build `compile_commands.json` database
        run: bazel run @hedron_compile_commands//:refresh_all

      - name: Workaround for Custom Docker Image
        run: git config --global --add safe.directory /__w/re-core/re-core

      - name: Generate Coverage Report
        run: bazel coverage ... --combined_report=lcov --java_runtime_version=remotejdk_11 --nocache_test_results --test_tag_filters="-integration"

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
